using System.Globalization;

namespace StreamVolumeGuard.Core.Localization;

public sealed class DesktopTextCatalog
{
    private DesktopTextCatalog(string languageCode)
    {
        LanguageCode = languageCode;
    }

    public string LanguageCode { get; }

    public static DesktopTextCatalog ForCurrentSystem()
    {
        return ForSystemLanguage(CultureInfo.CurrentUICulture.Name);
    }

    public static DesktopTextCatalog ForSystemLanguage(string? languageName)
    {
        return !string.IsNullOrWhiteSpace(languageName) &&
            languageName.StartsWith("fr", StringComparison.OrdinalIgnoreCase)
            ? French
            : English;
    }

    public static DesktopTextCatalog French { get; } = new("fr")
    {
        Subtitle = "Mixeur intelligent local pour toutes tes sources",
        AutoEnabled = "Auto actif",
        StreamSafe = "Stream Safe",
        Refresh = "Rafraichir",
        Panic = "Panic",
        TrustLocal = "Local",
        TrustOpenSource = "Open source",
        TrustNoTracking = "Zero tracking",
        TrustNoAccount = "Sans compte",
        WindowsSourcesTitle = "Sources Windows",
        BrowserSourcesTitle = "Sources navigateur",
        CoverageTitle = "Couverture",
        WatchTitle = "A surveiller",
        ModeTitle = "Mode",
        ExtensionLinkLabel = "Liaison extension",
        GlobalOutputTitle = "Sortie globale",
        StateTitle = "Etat",
        CurrentLevelTitle = "Niveau actuel",
        TargetVolumeTitle = "Cible volume",
        TargetQuiet = "Calme",
        TargetStandard = "Standard",
        TargetLoud = "Fort",
        TargetScope = "Windows + navigateur",
        WindowsAppsTitle = "Applications Windows",
        WindowsAppsDescription = "Mixeur Windows intelligent : volume manuel, statut, exclusions et controle reel.",
        BrowserAppsDescription = "Detail par onglet/site quand l'extension et le bridge local peuvent l'observer.",
        SourceHeader = "Source",
        StatusHeader = "Statut",
        PeakHeader = "Pic",
        VolumeHeader = "Volume",
        ControlHeader = "Controle",
        ControllableHeader = "Controlable",
        CoverageHeader = "Couverture",
        CoverageActionHeader = "Action couverture",
        ExcludedHeader = "Exclu",
        ActionHeader = "Action",
        BrowserHeader = "Navigateur",
        SiteHeader = "Site",
        LevelHeader = "Niveau",
        GainHeader = "Gain",
        CalibrationHeader = "Calibration",
        ReasonHeader = "Raison",
        TitleHeader = "Titre",
        DebugTitle = "Debug",
        LogStatusReady = "Logs locaux prets.",
        BridgePendingStart = "Bridge local en attente de demarrage.",
        NewTest = "Nouveau test",
        GuidedStart = "Demarrer guide",
        GuidedNext = "Etape suivante",
        MarkStep = "Etape",
        CopyLogs = "Copier logs",
        OpenLogs = "Ouvrir logs",
        ObsGuide = "Guide OBS",
        Simulate = "Simuler",
        NewTestTooltip = "Creer une session de test propre",
        GuidedStartTooltip = "Mode test guide : YouTube, TikTok, Spotify, Discord, VLC, jeu, OBS",
        GuidedNextTooltip = "Passer a la source suivante du mode test guide",
        MarkStepTooltip = "Marquer une etape dans les logs",
        CopyLogsTooltip = "Copier les logs de la session de test",
        OpenLogsTooltip = "Ouvrir le dossier des logs locaux",
        ObsGuideTooltip = "Afficher le setup OBS Stream Safety",
        SimulateTooltip = "Simuler une source navigateur pour tester le bridge",
        GuidedTestReady = "Mode test guide pret : commence par YouTube.",
        ThemeLightButton = "Mode clair",
        ThemeDarkButton = "Mode sombre",
        ThemeLightStatus = "Theme clair",
        ThemeDarkStatus = "Theme sombre",
        TargetBridgeDefault = "Cible partagee avec l'extension via le bridge local.",
        ExtensionStandalone = "App seule : extension non connectee.",
        ExtensionConnected = "Extension connectee : detail navigateur disponible.",
        ExtensionStandaloneGlobal = "App seule : controle Windows global, extension non connectee.",
        GlobalOutputUnknownState = "Unknown",
        GlobalOutputRmsUnknown = "RMS inconnu",
        GlobalOutputPeakUnknown = "Pic inconnu",
        GlobalOutputDeviceUnknown = "Sortie inconnue",
        GlobalOutputWaiting = "Lecture seule : en attente de capture loopback.",
        Yes = "Oui",
        No = "Non",
        Unknown = "Inconnu",
        SourceSingular = "source",
        WatchSuffix = "a surveiller",
        ObservationMode = "Observation",
        ObserveAbbreviation = "Obs",
        BrowserInsufficientSignal = "Signal navigateur insuffisant",
        BrowserRestrictedPage = "Page navigateur restreinte",
        BrowserCaptureUnavailable = "Capture navigateur indisponible",
        BrowserControlUnknown = "Controle navigateur inconnu",
        BrowserControlAvailable = "Controle disponible",
        BrowserDirectControlUnavailable = "Controle direct indisponible",
        BrowserFallbackWindows = "fallback Windows",
        BrowserMeasuring = "mesure",
        VerifyLogsThenObs = "Verifier logs puis tester OBS",
        DirectControl = "Direct",
        WindowsFallback = "Fallback Windows",
        ActionRequired = "Action requise",
        Limited = "Limite",
        OkDirect = "OK direct",
        UseObsSeparateCapture = "Utilise OBS / capture separee",
        BrowserGainActive = "BrowserGain actif",
        BrowserCalibrationInProgress = "Calibration en cours",
        TabActivationRequired = "Activation onglet requise",
        ObserveOnlySource = "Source observee seulement",
        KeepBrowserGain = "Laisser BrowserGain agir",
        WaitForMeasurement = "Attendre la mesure 18-20 s",
        ClickProtectActiveTab = "Cliquer Proteger l'onglet actif",
        UseChromeOrFallback = "Utiliser Chrome/Brave/Edge ou fallback Windows",
        ReloadReprotectFallback = "Recharger, reproteger, sinon fallback Windows",
        PlayTab = "Mettre l'onglet en lecture"
    };

    public static DesktopTextCatalog English { get; } = new("en")
    {
        Subtitle = "Intelligent local mixer for all your sources",
        AutoEnabled = "Auto on",
        StreamSafe = "Stream Safe",
        Refresh = "Refresh",
        Panic = "Panic",
        TrustLocal = "Local",
        TrustOpenSource = "Open source",
        TrustNoTracking = "No tracking",
        TrustNoAccount = "No account",
        WindowsSourcesTitle = "Windows sources",
        BrowserSourcesTitle = "Browser sources",
        CoverageTitle = "Coverage",
        WatchTitle = "Needs attention",
        ModeTitle = "Mode",
        ExtensionLinkLabel = "Extension link",
        GlobalOutputTitle = "Global output",
        StateTitle = "State",
        CurrentLevelTitle = "Current level",
        TargetVolumeTitle = "Volume target",
        TargetQuiet = "Quiet",
        TargetStandard = "Standard",
        TargetLoud = "Loud",
        TargetScope = "Windows + browser",
        WindowsAppsTitle = "Windows applications",
        WindowsAppsDescription = "Smart Windows mixer: manual volume, status, exclusions, and real control.",
        BrowserAppsDescription = "Tab/site detail when the extension and local bridge can observe it.",
        SourceHeader = "Source",
        StatusHeader = "Status",
        PeakHeader = "Peak",
        VolumeHeader = "Volume",
        ControlHeader = "Control",
        ControllableHeader = "Controllable",
        CoverageHeader = "Coverage",
        CoverageActionHeader = "Coverage action",
        ExcludedHeader = "Excluded",
        ActionHeader = "Action",
        BrowserHeader = "Browser",
        SiteHeader = "Site",
        LevelHeader = "Level",
        GainHeader = "Gain",
        CalibrationHeader = "Calibration",
        ReasonHeader = "Reason",
        TitleHeader = "Title",
        DebugTitle = "Debug",
        LogStatusReady = "Local logs ready.",
        BridgePendingStart = "Local bridge waiting to start.",
        NewTest = "New test",
        GuidedStart = "Start guide",
        GuidedNext = "Next step",
        MarkStep = "Step",
        CopyLogs = "Copy logs",
        OpenLogs = "Open logs",
        ObsGuide = "OBS guide",
        Simulate = "Simulate",
        NewTestTooltip = "Create a clean test session",
        GuidedStartTooltip = "Guided test mode: YouTube, TikTok, Spotify, Discord, VLC, game, OBS",
        GuidedNextTooltip = "Move to the next guided-test source",
        MarkStepTooltip = "Mark a step in the logs",
        CopyLogsTooltip = "Copy current test-session logs",
        OpenLogsTooltip = "Open the local logs folder",
        ObsGuideTooltip = "Show the OBS Stream Safety setup",
        SimulateTooltip = "Simulate a browser source to test the bridge",
        GuidedTestReady = "Guided test mode ready: start with YouTube.",
        ThemeLightButton = "Light mode",
        ThemeDarkButton = "Dark mode",
        ThemeLightStatus = "Light theme",
        ThemeDarkStatus = "Dark theme",
        TargetBridgeDefault = "Target shared with the extension through the local bridge.",
        ExtensionStandalone = "App only: extension not connected.",
        ExtensionConnected = "Extension connected: browser detail available.",
        ExtensionStandaloneGlobal = "App only: global Windows control, extension not connected.",
        GlobalOutputUnknownState = "Unknown",
        GlobalOutputRmsUnknown = "RMS unknown",
        GlobalOutputPeakUnknown = "Peak unknown",
        GlobalOutputDeviceUnknown = "Unknown output",
        GlobalOutputWaiting = "Read only: waiting for loopback capture.",
        Yes = "Yes",
        No = "No",
        Unknown = "Unknown",
        SourceSingular = "source",
        WatchSuffix = "to watch",
        ObservationMode = "Observation",
        ObserveAbbreviation = "Obs",
        BrowserInsufficientSignal = "Insufficient browser signal",
        BrowserRestrictedPage = "Restricted browser page",
        BrowserCaptureUnavailable = "Browser capture unavailable",
        BrowserControlUnknown = "Unknown browser control",
        BrowserControlAvailable = "Control available",
        BrowserDirectControlUnavailable = "Direct control unavailable",
        BrowserFallbackWindows = "Windows fallback",
        BrowserMeasuring = "measuring",
        VerifyLogsThenObs = "Check logs, then test OBS",
        DirectControl = "Direct",
        WindowsFallback = "Windows fallback",
        ActionRequired = "Action required",
        Limited = "Limited",
        OkDirect = "Direct OK",
        UseObsSeparateCapture = "Use OBS / separate capture",
        BrowserGainActive = "BrowserGain active",
        BrowserCalibrationInProgress = "Calibration in progress",
        TabActivationRequired = "Tab activation required",
        ObserveOnlySource = "Observed only",
        KeepBrowserGain = "Let BrowserGain work",
        WaitForMeasurement = "Wait for the 18-20 s measurement",
        ClickProtectActiveTab = "Click Protect active tab",
        UseChromeOrFallback = "Use Chrome/Brave/Edge or Windows fallback",
        ReloadReprotectFallback = "Reload, protect again, otherwise Windows fallback",
        PlayTab = "Start playback in the tab"
    };

    public string Subtitle { get; private init; } = string.Empty;
    public string AutoEnabled { get; private init; } = string.Empty;
    public string StreamSafe { get; private init; } = string.Empty;
    public string Refresh { get; private init; } = string.Empty;
    public string Panic { get; private init; } = string.Empty;
    public string TrustLocal { get; private init; } = string.Empty;
    public string TrustOpenSource { get; private init; } = string.Empty;
    public string TrustNoTracking { get; private init; } = string.Empty;
    public string TrustNoAccount { get; private init; } = string.Empty;
    public string WindowsSourcesTitle { get; private init; } = string.Empty;
    public string BrowserSourcesTitle { get; private init; } = string.Empty;
    public string CoverageTitle { get; private init; } = string.Empty;
    public string WatchTitle { get; private init; } = string.Empty;
    public string ModeTitle { get; private init; } = string.Empty;
    public string ExtensionLinkLabel { get; private init; } = string.Empty;
    public string GlobalOutputTitle { get; private init; } = string.Empty;
    public string StateTitle { get; private init; } = string.Empty;
    public string CurrentLevelTitle { get; private init; } = string.Empty;
    public string TargetVolumeTitle { get; private init; } = string.Empty;
    public string TargetQuiet { get; private init; } = string.Empty;
    public string TargetStandard { get; private init; } = string.Empty;
    public string TargetLoud { get; private init; } = string.Empty;
    public string TargetScope { get; private init; } = string.Empty;
    public string WindowsAppsTitle { get; private init; } = string.Empty;
    public string WindowsAppsDescription { get; private init; } = string.Empty;
    public string BrowserAppsDescription { get; private init; } = string.Empty;
    public string SourceHeader { get; private init; } = string.Empty;
    public string StatusHeader { get; private init; } = string.Empty;
    public string PeakHeader { get; private init; } = string.Empty;
    public string VolumeHeader { get; private init; } = string.Empty;
    public string ControlHeader { get; private init; } = string.Empty;
    public string ControllableHeader { get; private init; } = string.Empty;
    public string CoverageHeader { get; private init; } = string.Empty;
    public string CoverageActionHeader { get; private init; } = string.Empty;
    public string ExcludedHeader { get; private init; } = string.Empty;
    public string ActionHeader { get; private init; } = string.Empty;
    public string BrowserHeader { get; private init; } = string.Empty;
    public string SiteHeader { get; private init; } = string.Empty;
    public string LevelHeader { get; private init; } = string.Empty;
    public string GainHeader { get; private init; } = string.Empty;
    public string CalibrationHeader { get; private init; } = string.Empty;
    public string ReasonHeader { get; private init; } = string.Empty;
    public string TitleHeader { get; private init; } = string.Empty;
    public string DebugTitle { get; private init; } = string.Empty;
    public string LogStatusReady { get; private init; } = string.Empty;
    public string BridgePendingStart { get; private init; } = string.Empty;
    public string NewTest { get; private init; } = string.Empty;
    public string GuidedStart { get; private init; } = string.Empty;
    public string GuidedNext { get; private init; } = string.Empty;
    public string MarkStep { get; private init; } = string.Empty;
    public string CopyLogs { get; private init; } = string.Empty;
    public string OpenLogs { get; private init; } = string.Empty;
    public string ObsGuide { get; private init; } = string.Empty;
    public string Simulate { get; private init; } = string.Empty;
    public string NewTestTooltip { get; private init; } = string.Empty;
    public string GuidedStartTooltip { get; private init; } = string.Empty;
    public string GuidedNextTooltip { get; private init; } = string.Empty;
    public string MarkStepTooltip { get; private init; } = string.Empty;
    public string CopyLogsTooltip { get; private init; } = string.Empty;
    public string OpenLogsTooltip { get; private init; } = string.Empty;
    public string ObsGuideTooltip { get; private init; } = string.Empty;
    public string SimulateTooltip { get; private init; } = string.Empty;
    public string GuidedTestReady { get; private init; } = string.Empty;
    public string ThemeLightButton { get; private init; } = string.Empty;
    public string ThemeDarkButton { get; private init; } = string.Empty;
    public string ThemeLightStatus { get; private init; } = string.Empty;
    public string ThemeDarkStatus { get; private init; } = string.Empty;
    public string TargetBridgeDefault { get; private init; } = string.Empty;
    public string ExtensionStandalone { get; private init; } = string.Empty;
    public string ExtensionConnected { get; private init; } = string.Empty;
    public string ExtensionStandaloneGlobal { get; private init; } = string.Empty;
    public string GlobalOutputUnknownState { get; private init; } = string.Empty;
    public string GlobalOutputRmsUnknown { get; private init; } = string.Empty;
    public string GlobalOutputPeakUnknown { get; private init; } = string.Empty;
    public string GlobalOutputDeviceUnknown { get; private init; } = string.Empty;
    public string GlobalOutputWaiting { get; private init; } = string.Empty;
    public string Yes { get; private init; } = string.Empty;
    public string No { get; private init; } = string.Empty;
    public string Unknown { get; private init; } = string.Empty;
    public string SourceSingular { get; private init; } = string.Empty;
    public string WatchSuffix { get; private init; } = string.Empty;
    public string ObservationMode { get; private init; } = string.Empty;
    public string ObserveAbbreviation { get; private init; } = string.Empty;
    public string BrowserInsufficientSignal { get; private init; } = string.Empty;
    public string BrowserRestrictedPage { get; private init; } = string.Empty;
    public string BrowserCaptureUnavailable { get; private init; } = string.Empty;
    public string BrowserControlUnknown { get; private init; } = string.Empty;
    public string BrowserControlAvailable { get; private init; } = string.Empty;
    public string BrowserDirectControlUnavailable { get; private init; } = string.Empty;
    public string BrowserFallbackWindows { get; private init; } = string.Empty;
    public string BrowserMeasuring { get; private init; } = string.Empty;
    public string VerifyLogsThenObs { get; private init; } = string.Empty;
    public string DirectControl { get; private init; } = string.Empty;
    public string WindowsFallback { get; private init; } = string.Empty;
    public string ActionRequired { get; private init; } = string.Empty;
    public string Limited { get; private init; } = string.Empty;
    public string OkDirect { get; private init; } = string.Empty;
    public string UseObsSeparateCapture { get; private init; } = string.Empty;
    public string BrowserGainActive { get; private init; } = string.Empty;
    public string BrowserCalibrationInProgress { get; private init; } = string.Empty;
    public string TabActivationRequired { get; private init; } = string.Empty;
    public string ObserveOnlySource { get; private init; } = string.Empty;
    public string KeepBrowserGain { get; private init; } = string.Empty;
    public string WaitForMeasurement { get; private init; } = string.Empty;
    public string ClickProtectActiveTab { get; private init; } = string.Empty;
    public string UseChromeOrFallback { get; private init; } = string.Empty;
    public string ReloadReprotectFallback { get; private init; } = string.Empty;
    public string PlayTab { get; private init; } = string.Empty;

    public IReadOnlyDictionary<string, string> ToResourceMap()
    {
        return new Dictionary<string, string>(StringComparer.Ordinal)
        {
            ["SubtitleText"] = Subtitle,
            ["AutoEnabledText"] = AutoEnabled,
            ["StreamSafeText"] = StreamSafe,
            ["RefreshText"] = Refresh,
            ["PanicText"] = Panic,
            ["TrustLocalText"] = TrustLocal,
            ["TrustOpenSourceText"] = TrustOpenSource,
            ["TrustNoTrackingText"] = TrustNoTracking,
            ["TrustNoAccountText"] = TrustNoAccount,
            ["WindowsSourcesTitleText"] = WindowsSourcesTitle,
            ["BrowserSourcesTitleText"] = BrowserSourcesTitle,
            ["CoverageTitleText"] = CoverageTitle,
            ["WatchTitleText"] = WatchTitle,
            ["ModeTitleText"] = ModeTitle,
            ["ExtensionLinkLabelText"] = ExtensionLinkLabel,
            ["GlobalOutputTitleText"] = GlobalOutputTitle,
            ["StateTitleText"] = StateTitle,
            ["CurrentLevelTitleText"] = CurrentLevelTitle,
            ["TargetVolumeTitleText"] = TargetVolumeTitle,
            ["TargetQuietText"] = TargetQuiet,
            ["TargetStandardText"] = TargetStandard,
            ["TargetLoudText"] = TargetLoud,
            ["TargetScopeText"] = TargetScope,
            ["WindowsAppsTitleText"] = WindowsAppsTitle,
            ["WindowsAppsDescriptionText"] = WindowsAppsDescription,
            ["BrowserAppsDescriptionText"] = BrowserAppsDescription,
            ["SourceHeaderText"] = SourceHeader,
            ["StatusHeaderText"] = StatusHeader,
            ["PeakHeaderText"] = PeakHeader,
            ["VolumeHeaderText"] = VolumeHeader,
            ["ControlHeaderText"] = ControlHeader,
            ["ControllableHeaderText"] = ControllableHeader,
            ["CoverageHeaderText"] = CoverageHeader,
            ["CoverageActionHeaderText"] = CoverageActionHeader,
            ["ExcludedHeaderText"] = ExcludedHeader,
            ["ActionHeaderText"] = ActionHeader,
            ["BrowserHeaderText"] = BrowserHeader,
            ["SiteHeaderText"] = SiteHeader,
            ["LevelHeaderText"] = LevelHeader,
            ["GainHeaderText"] = GainHeader,
            ["CalibrationHeaderText"] = CalibrationHeader,
            ["ReasonHeaderText"] = ReasonHeader,
            ["TitleHeaderText"] = TitleHeader,
            ["DebugTitleText"] = DebugTitle,
            ["LogStatusReadyText"] = LogStatusReady,
            ["BridgePendingStartText"] = BridgePendingStart,
            ["NewTestText"] = NewTest,
            ["GuidedStartText"] = GuidedStart,
            ["GuidedNextText"] = GuidedNext,
            ["MarkStepText"] = MarkStep,
            ["CopyLogsText"] = CopyLogs,
            ["OpenLogsText"] = OpenLogs,
            ["ObsGuideText"] = ObsGuide,
            ["SimulateText"] = Simulate,
            ["NewTestTooltipText"] = NewTestTooltip,
            ["GuidedStartTooltipText"] = GuidedStartTooltip,
            ["GuidedNextTooltipText"] = GuidedNextTooltip,
            ["MarkStepTooltipText"] = MarkStepTooltip,
            ["CopyLogsTooltipText"] = CopyLogsTooltip,
            ["OpenLogsTooltipText"] = OpenLogsTooltip,
            ["ObsGuideTooltipText"] = ObsGuideTooltip,
            ["GuidedTestReadyText"] = GuidedTestReady,
            ["SimulateTooltipText"] = SimulateTooltip
        };
    }
}
